2.2/user login
rruzicic/globetrotter pull request #14
Opened 2023-03-21 20:10 UTC by rruzicic

# Changelog
- Add user login using JWT tokens
- Add configuration management using viper
- Send HTTP request from frontend to backend for login and registration

**WARNING:** ~~Not thoroughly tested~~ Not tested ..... at all

2023-03-22 20:19 UTC, Vlodson requested changes
Can't review FE files because I don't know FE so I'll hope it works

2023-03-22 20:19 UTC, Vlodson commented on flights/backend/config/config.env
> +PORT=":8080"
Newline

2023-03-22 20:19 UTC, Vlodson commented on flights/backend/models/user.go
> +const AdminRole = "ADMIN"
Add [enums](https://www.sohamkamani.com/golang/enums/) instead of this

2023-03-25 08:36 UTC, rruzicic commented on flights/backend/repos/user_repo.go
> +func FindUserByEmail(email string) (models.User, error) {
We actually had two methods that did the same thing one was `FindUserByEmail` and the other was `FindUserByMail` so I just deleted one of them

2023-03-25 09:50 UTC, Vlodson requested changes

2023-03-25 09:50 UTC, Vlodson commented on flights/backend/services/user_service.go
>  func FindUserByMail(mail string) (*models.User, error) {
Very minor: change name to FindUserByEmail to match the one from the repo

2023-03-25 11:27 UTC, merged